# Generated by Django 5.1.2 on 2025-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberSecurityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='isAll',
            field=models.BooleanField(default=True),
        ),
    ]
