# Generated by Django 5.1.2 on 2025-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CyberSecurityApp', '0002_analysisresult_isall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ImageField(upload_to='parts/'),
        ),
    ]
